#-----------------------------------------------------------------------
version: '3.7'
#-----------------------------------------------------------------------
services:
#-----------------------------------------------------------------------
  python:
    image: ${repoUser}/${repoName}:${appName}
    command: python manage.py runserver -h 0.0.0.0 -p 8080
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.hostname==${deployNode}
      restart_policy:
        condition: any
    networks:
      - appnet
      - webnet
#-----------------------------------------------------------------------
networks:
  appnet:
    external: true
    name: CICD_appnet
  webnet:
    external: true
    name: CICD_webnet
