#-----------------------------------------------------------------------
version: '3.7'
#-----------------------------------------------------------------------
services:
#-----------------------------------------------------------------------
  ${appName}:
    image: ${repoUser}/${repoName}:${appName}
    command: POSTMARK_KEY="${postmarkKey}" yarn start
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.hostname==${deployNode}
      restart_policy:
        condition: any
    networks:
      - appnet
      - webnet
#-----------------------------------------------------------------------
networks:
  appnet:
    external: true
    name: CICD_appnet
  webnet:
    external: true
    name: CICD_webnet
